id: P34ACB334
initial_creation_type: input
source_metadata:
  title: Sickness and Healing
  language: fr
  description: 'Lotsawa House presents the following texts as part of our Sickness
    and Healing Series:'
  volume:
    41d4ba55e5f945508289a0c82a09a190:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    c75c215310d642beb17fef277f01a3e6:
      title: How to Transform Sickness and Other Circumstances
      parent: Advice
    0b333b30239e48bca2af99fb0be9a456:
      title: The Universal Medicine for Healing All Ills
      parent: Advice
    2c08bf6dbe40489d9edabbda04be03f3:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    cca0cac8df884683860ec22786a9b17f:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    a024d06e1c8c4cd4a2fe8e8bce66deb0:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Practices
    6294630bc0ac43b9a7c29263a0d57c15:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Practices
    9c229a48c2ba4411a7bd5ae32b68e1e7:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Practices
    90e37ad608c24436b78d1de496f037eb:
      title: Daily Practice of Dorje Gotrab
      parent: Practices
    0e78fdf03774458c8552ebabec7ef1b7:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Practices
    3ff487cee6da4613908b1c0e842c76a9:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Practices
    ce94616c8b3e4828b943e68f7b425972:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    6d0cdc9b54af4009ac704df2e84c4f41:
      title: Acala Sādhana
      parent: Practices
    4c226792035247f1a7f68201be7f1691:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Practices
    0cde4bb05f0549dc9e6aa244d2148a38:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
created_at: '2022-03-01T05:47:13.660930'
last_modified_at: '2022-03-01T05:47:13.660933'
